version: "3"
services:
  app:
    build: ./app
    ports: 
      - "8080:8080"
      - "8443:8443"
    volumes: 
      - ./app/app:/app
    command: code-server --auth none --host 0.0.0.0 --port 8443 /app
